### ISSUE TITLE
How to actually install dvm?

### ISSUE THREAD

**Issue by RadoslavL** [diced/dvm#3]
I am very new to rust and am unable to find the proper way to install this CLI tool. Which of the files is the actual program?

**Comment by advilm** [comment]
You can download a binary from the releases tab. [Current latest release.](https://github.com/diced/dvm/releases/tag/1.1.8)
If you want to build it you need to install cargo (rust's package manager) and run `cargo build --release`. The release file will be in the target folder.

**Comment by diced** [comment]
What distro do you use?

If you are on Arch Linux then you can use the aur package `dvm` (installs binary) or `dvm-git` (compiles from source)

**Comment by RadoslavL** [comment]
@diced I am sorry for asking a dumb question, I am just used to repositories having their binaries in the files and not in the releases. Thanks!

**Comment by diced** [comment]
I've added a section to the README that outlines how to install dvm with different ways, hopefully its more clear now!
